[package]
name = "riprocess"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
docopt = "1.1"
lazy_static = "0.2"
regex = "1.8"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[[bin]]
name = "riprocess"
doc = false
test = false
