[package]
name = "riprocess"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
lazy_static = "*"
regex = "*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[[bin]]
name = "riprocess"
doc = false
test = false
